---
model:
  hidden_dim: 1024
  use_pretrain_embed: false
  embedding_dim: 200
  resume_train: false
  model_path: "ckpt"
  saved_epoch: 22
  pb_path: "pb"
  max_epoch_num: 30
  beam_width: 10
  learning_rate: 0.0003
data:
  vocab_max_size: 10000
  vocab_min_freq: 10
  input_step: 30
  max_decode_step: 30
  batch_size: 64