---
model:
  hidden_dim: 1024
  use_pretrain_embed: false
  embedding_dim: 200
  resume_train: false
  model_path: "saved_model"
  max_epoch_num: 5
  beam_width: 10
  learning_rate: 0.0003
data:
  vocab_max_size: 10000
  vocab_min_freq: 10
  max_input_step: 30
  batch_size: 64